# Generated by Django 5.1.2 on 2024-10-28 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_user_is_staff'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
